/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-03-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public with sharing class GenerateSObjectFieldMappingTest {
    
    @isTest
    static void insertObjectFieldMappingTest(){
        GenerateSObjectFieldMapping.insertObjectFieldMapping();
    }
}